In [1]:
import pandas as pd
data = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',names=['sepal_length','sepal_width','petal_length','petal_width','species'])
data.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
# species is dependent variables and resta are independendent varaibles

In [13]:
X = data[['sepal_length','sepal_width','petal_length','petal_width']]
Y = data['species']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

# test-size 0.2 i.e testing data is 20 % and automatically training data becomes 80%.
# randomstate - controls the shuffling process. With random_state=None , we get different train and test sets across different executions and the shuffling process is out of control. With random_state=0 , we get the same train and test sets across different executions.

# it is like seed function in random
# matlab desi mei - ek number ke liye state fix ho jaegii
X_train
# this is training data

     sepal_length  sepal_width  petal_length  petal_width
126           6.2          2.8           4.8          1.8
23            5.1          3.3           1.7          0.5
64            5.6          2.9           3.6          1.3
117           7.7          3.8           6.7          2.2
84            5.4          3.0           4.5          1.5
..            ...          ...           ...          ...
75            6.6          3.0           4.4          1.4
43            5.0          3.5           1.6          0.6
22            4.6          3.6           1.0          0.2
72            6.3          2.5           4.9          1.5
15            5.7          4.4           1.5          0.4

[120 rows x 4 columns]

In [11]:
X_test
# it is inde var and used for testing

     sepal_length  sepal_width  petal_length  petal_width
6             4.6          3.4           1.4          0.3
3             4.6          3.1           1.5          0.2
113           5.7          2.5           5.0          2.0
12            4.8          3.0           1.4          0.1
24            4.8          3.4           1.9          0.2
129           7.2          3.0           5.8          1.6
25            5.0          3.0           1.6          0.2
108           6.7          2.5           5.8          1.8
128           6.4          2.8           5.6          2.1
45            4.8          3.0           1.4          0.3
48            5.3          3.7           1.5          0.2
42            4.4          3.2           1.3          0.2
35            5.0          3.2           1.2          0.2
5             5.4          3.9           1.7          0.4
85            6.0          3.4           4.5          1.6
54            6.5          2.8           4.6          1.5
41            4.5          2.3           1.3          0.3
96            5.7          2.9           4.2          1.3
144           6.7          3.3           5.7          2.5
89            5.5          2.5           4.0          1.3
77            6.7          3.0           5.0          1.7
74            6.4          2.9           4.3          1.3
115           6.4          3.2           5.3          2.3
94            5.6          2.7           4.2          1.3
87            6.3          2.3           4.4          1.3
29            4.7          3.2           1.6          0.2
2             4.7          3.2           1.3          0.2
127           6.1          3.0           4.9          1.8
44            5.1          3.8           1.9          0.4
125           7.2          3.2           6.0          1.8

In [12]:
Y_test

6          Iris-setosa
3          Iris-setosa
113     Iris-virginica
12         Iris-setosa
24         Iris-setosa
129     Iris-virginica
25         Iris-setosa
108     Iris-virginica
128     Iris-virginica
45         Iris-setosa
48         Iris-setosa
42         Iris-setosa
35         Iris-setosa
5          Iris-setosa
85     Iris-versicolor
54     Iris-versicolor
41         Iris-setosa
96     Iris-versicolor
144     Iris-virginica
89     Iris-versicolor
77     Iris-versicolor
74     Iris-versicolor
115     Iris-virginica
94     Iris-versicolor
87     Iris-versicolor
29         Iris-setosa
2          Iris-setosa
127     Iris-virginica
44         Iris-setosa
125     Iris-virginica
Name: species, dtype: object

In [14]:
X_test.count()

sepal_length    30
sepal_width     30
petal_length    30
petal_width     30
dtype: int64

In [15]:
X_train.count()

sepal_length    120
sepal_width     120
petal_length    120
petal_width     120
dtype: int64

In [16]:
Y_test.count()

30

In [17]:
Y_train.count()

120